- name: Fronted setup
  host: All
  tasks: Install Nginx
    - name: Installing Nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Placing Expense Config File in Nginx
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: Removing Old Nginx Service
    - name: Download fronted Code
    - name: Extracting fronted Code
    - name: Starting Nginx Service








  source common.sh
  component=frontend
  
  echo Installing Nginx
  dnf install nginx -y &>>$log_file
  stat_check
  
  
  echo Placing Expense Config File in Nginx
  cp expense.conf /etc/nginx/default.d/expense.conf &>>$log_file
  stat_check
  
  echo Removing Old Nginx content
  rm -rf /usr/share/nginx/html/* &>>$log_file
  stat_check
  
  cd /usr/share/nginx/html
  
  download_and_extract
  
  echo Starting Nginx Service
  systemctl enable nginx &>>$log_file
  systemctl restart nginx &>>$log_file
  stat_check